export default {
    name:"project",
    title:"Project",
    type:"document",
    fields:[{
        name:"title",
        type:"string"
    },
    {
        name:"date",
        type:"datetime"
    },
    {
        name:"languages",
        type:"text"
    },
    {
        name:"description",
        type:"text"
    },
    {
        name:"link",
        type:"url"
    },
    {
        name:"photoLink",
        type:"url"
    },
    {
        name:"dataManagement",
        type:"string"
    }
    ,
    {
        name:"technologies",
        type:"string"
    }
    ]

}